namespace Smart.Navigation.Generator.Tests;

using Microsoft.CodeAnalysis;

public class NavigationGeneratorTest
{
    //-----------------------------------------------------------------------
    // Basic
    //-----------------------------------------------------------------------

    [Fact]
    public void BasicViewSourceGeneratesPartialMethod()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1,
                Form2
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            [View(ViewId.Form2)]
            public sealed class Form2
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("partial class ViewRegistry", generated, StringComparison.Ordinal);
        Assert.Contains("public static partial global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<global::Test.ViewId, global::System.Type>> ListViews()", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void BasicViewSourceGeneratesAutoGeneratedHeader()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("// <auto-generated />", generated, StringComparison.Ordinal);
        Assert.Contains("#nullable enable", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void BasicViewSourceGeneratesNamespace()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("namespace Test;", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void BasicViewSourceGeneratesYieldReturnForView()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("yield return new global::System.Collections.Generic.KeyValuePair<global::Test.ViewId, global::System.Type>(Test.ViewId.Form1, typeof(global::Test.Form1));", generated, StringComparison.Ordinal);
    }

    //-----------------------------------------------------------------------
    // Multiple
    //-----------------------------------------------------------------------

    [Fact]
    public void MultipleViewsGenerateMultipleYieldReturns()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1,
                Form2
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            [View(ViewId.Form2)]
            public sealed class Form2
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("typeof(global::Test.Form1)", generated, StringComparison.Ordinal);
        Assert.Contains("typeof(global::Test.Form2)", generated, StringComparison.Ordinal);
        Assert.Equal(2, CountOccurrences(generated, "yield return"));
    }

    //-----------------------------------------------------------------------
    // AllowMultiple
    //-----------------------------------------------------------------------

    [Fact]
    public void MultipleViewAttributesOnSingleClassGenerateMultipleYieldReturns()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                New,
                Update
            }

            [View(ViewId.New)]
            [View(ViewId.Update)]
            public sealed class DetailView
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("Test.ViewId.New, typeof(global::Test.DetailView)", generated, StringComparison.Ordinal);
        Assert.Contains("Test.ViewId.Update, typeof(global::Test.DetailView)", generated, StringComparison.Ordinal);
        Assert.Equal(2, CountOccurrences(generated, "yield return"));
    }

    //-----------------------------------------------------------------------
    // Method accessibility
    //-----------------------------------------------------------------------

    [Fact]
    public void InternalViewSourceGeneratesInternalMethod()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                internal static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("internal static partial", generated, StringComparison.Ordinal);
    }

    //-----------------------------------------------------------------------
    // Value type container
    //-----------------------------------------------------------------------

    [Fact]
    public void ValueTypeContainerGeneratesPartialStruct()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public partial struct ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Contains("partial struct ViewRegistry", generated, StringComparison.Ordinal);
    }

    //-----------------------------------------------------------------------
    // No matching
    //-----------------------------------------------------------------------

    [Fact]
    public void NoMatchingViewDoesNotGenerateSource()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var generated = GeneratorTestHelper.GetGeneratedSource(source);

        Assert.Equal(string.Empty, generated);
    }

    //-----------------------------------------------------------------------
    // No errors
    //-----------------------------------------------------------------------

    [Fact]
    public void BasicViewSourceOutputCompilationHasNoErrors()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1,
                Form2
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            [View(ViewId.Form2)]
            public sealed class Form2
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnosticsAll(source);

        Assert.DoesNotContain(diagnostics, d => d.Severity == DiagnosticSeverity.Error);
    }

    //-----------------------------------------------------------------------
    // Diagnostics
    //-----------------------------------------------------------------------

    [Fact]
    public void Snv0001NonStaticMethodEmitsDiagnostic()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            public partial class ViewRegistry
            {
                [ViewSource]
                public partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

        Assert.Contains(diagnostics, d => d.Id == "SNV0001");
    }

    [Fact]
    public void Snv0001NonPartialMethodEmitsDiagnostic()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            public static class ViewRegistry
            {
                [ViewSource]
                public static IEnumerable<KeyValuePair<ViewId, Type>> ListViews() => null!;
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

        Assert.Contains(diagnostics, d => d.Id == "SNV0001");
    }

    [Fact]
    public void Snv0002MethodWithParameterEmitsDiagnostic()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews(int dummy);
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

        Assert.Contains(diagnostics, d => d.Id == "SNV0002");
    }

    [Fact]
    public void Snv0003InvalidReturnTypeEmitsDiagnostic()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<int> ListViews();
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

        Assert.Contains(diagnostics, d => d.Id == "SNV0003");
    }

    [Fact]
    public void ValidViewSourceEmitsNoDiagnostic()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Smart.Navigation.Attributes;

            namespace Test;

            public enum ViewId
            {
                Form1
            }

            [View(ViewId.Form1)]
            public sealed class Form1
            {
            }

            public static partial class ViewRegistry
            {
                [ViewSource]
                public static partial IEnumerable<KeyValuePair<ViewId, Type>> ListViews();
            }
            """;

        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

        Assert.Empty(diagnostics);
    }

    //-----------------------------------------------------------------------
    // Helper
    //-----------------------------------------------------------------------

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }
}
